[package]
name = "rws"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
sha1 = "0.10.6"
simdutf8 = "0.1.5"
thiserror = "2.0.11"
tokio = { version = "1.35.1", features = ["full", "test-util"] }
utf-8 = "0.7.6"
